[package]
name = "async-std-proxy"
version = "0.1.0"
authors = ["Gavrie Philipson <gavrie@philipson.co.il>"]
edition = "2018"

[dependencies]
async-std = { version = "1.6", features = ["attributes", "unstable"] }
async-macros = "2.0.0"
futures = "0.3"
stop-token = "0.1"